- name: Create metadata folders
  file: path={{ item }} state=directory mode=0744
  with_items:
    - "{{ backend_metadata_location }}"
    - "{{ frontend_metadata_location }}"
    - "{{ remote_metadata_location }}"

- name: Generating backend metadata
  shell:
    "{{ vopaas_env }}/bin/python {{ vopaas_env }}/bin/make_satosa_saml_metadata.py -b -o {{ backend_metadata_location }} {{ proxy_dir }}/proxy_conf.yaml chdir={{ proxy_dir }}"

- name: Generating frontend metadata
  shell:
    "{{ vopaas_env }}/bin/python {{ vopaas_env }}/bin/make_satosa_saml_metadata.py -f -o {{ frontend_metadata_location }} {{ proxy_dir }}/proxy_conf.yaml chdir={{ proxy_dir }}"
