- name: Create directories
  file: path={{ item }} state=directory mode=0744
  with_items:
    - "{{ cert_dir }}"
    - "{{ backend_plugin_dir }}"
    - "{{ frontend_plugin_dir }}"
    - "{{ proxy_dir }}"

- name: Copy all keys from certs
  copy: src={{ item }} dest={{ cert_dir }}/{{ item | basename }} mode=0444
  with_fileglob:
    - ../files/certs/*

- name: Add proxy config
  template: src=proxy_conf.yaml dest={{ proxy_dir }}/proxy_conf.yaml

- name: Add internal attributes config
  copy: src=internal_attributes.yaml dest={{ proxy_dir }}/internal_attributes.yaml

- name: Add all frontend plugins
  template: src={{ item }} dest={{ frontend_plugin_dir }}/{{ item | basename }}
  with_fileglob:
    - ../templates/plugins/frontends/*

- name: Add all backend plugins
  template: src={{ item }} dest={{ backend_plugin_dir }}/{{ item | basename }}
  with_fileglob:
    - ../templates/plugins/backends/*

- name: Add VOPaaS proxy job
  template: src=vopaas_proxy.conf dest=/etc/init/vopaas_proxy.conf
  sudo: Yes
