- hosts: all

  # Get home folder path
  pre_tasks:
    - name: Register home directory
      command: echo $HOME
      register: home
      sudo: No

  vars:
    # The vopaas proxy installation folder
    installation_dir: "{{ home.stdout }}/vopaas"
    # Where to save the python virtual environ
    vopaas_env: "{{ installation_dir }}/virtualenv"
    # Where the generated backend metadata should be placed
    backend_metadata_location: "{{ installation_dir }}/metadata/backend"
    # Where the generated frontend metadata should be placed
    frontend_metadata_location: "{{ installation_dir }}/metadata/frontend"

    # SATOSA config
 
    # Proxy host name
    proxy_hostname: "127.0.0.1"
    # Proxy port
    proxy_port: "9091"
    # Need to be global for when generating metadata
    proxy_dir: "{{ installation_dir }}/proxy"

    #Nginx config
    nginx_hostname: "{{ inventory_hostname }}"
    nginx_port: "443"

    # Need to be global for when generating metadata
    proxy_dir: "{{ installation_dir }}/proxy"

  roles:
    # Install nginx to handle ssl
    - {role: nginx, sudo: yes}
    # Install all python libraries to the virtual env
    - {role: install, sudo: yes}
    # Setup the proxy with configurations and module plugins
    - {role: setup, sudo: yes}
    # Generate metadata for the proxy frontend and backend
    - {role: generate_metadata, sudo: yes}
