- name: Create project directory
  file: path={{ installation_dir }} state=directory mode=0744

- name: install apt pkg
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - git
    - xmlsec1
    - libffi-dev
    - libssl-dev
    - libyaml-dev
    - python-dev
    - python-setuptools
    - python-pip
    - python3-pip
  sudo: Yes

- name: install virtualenv
  pip: name=virtualenv
  sudo: Yes

- name: create virtualenv
  command: virtualenv --python=/usr/bin/python3 {{ vopaas_env }}

- name: fetch VOPaaS from github
  git:
    repo=https://github.com/its-dirg/VOPaaS
    dest={{ vopaas_src_dir }}
    version=07c42f674dcb05fd7a62de764e8825617d0826a4
    force=yes

- name: install vopaas
  pip:
    name={{ vopaas_src_dir }} virtualenv={{ vopaas_env }}

- name: install requirements
  pip:
    requirements={{ vopaas_src_dir }}/requirements.txt virtualenv={{ vopaas_env }}
