- name: Create project directory
  file: path={{ installation_dir }} state=directory mode=0744

- name: install apt pkg
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - git
    - xmlsec1
    - libffi-dev
    - libssl-dev
    - libyaml-dev
    - python-dev
    - python-setuptools
    - python-pip
    - python3-pip
  sudo: Yes

- name: install virtualenv
  pip: name=virtualenv
  sudo: Yes

- name: create virtualenv
  command: virtualenv --python=/usr/bin/python3 {{ vopaas_env }}

- name: fetch jwkest from github
  git:
    repo=https://github.com/rohe/pyjwkest
    dest={{ external_dep_src_dir }}/jwkest
    version=6928cc9c4490389b91e064422e1fe2a7ad7cf5c8
    force=yes

- name: fetch pysaml2 from github
  git:
    repo=https://github.com/its-dirg/pysaml2
    dest={{ external_dep_src_dir }}/pysaml2
    version=0b1b3c7f2f92391b08c0c9b64ba2f1d6c6966dfa
    force=yes

- name: fetch pyoidc from github
  git:
    repo=https://github.com/its-dirg/pyoidc
    dest={{ external_dep_src_dir }}/pyoidc
    version=4ad7333d4afa0f2da82fdc761d8086a603f52597
    force=yes

- name: fetch SATOSA from github
  git:
    repo=https://github.com/its-dirg/SATOSA
    dest={{ external_dep_src_dir }}/satosa
    version=65ac2f4cc00a97db20267b849e109a417da1c215
    force=yes

- name: fetch VOPaaS from github
  git:
    repo=https://github.com/its-dirg/VOPaaS
    dest={{ vopaas_src_dir }}
    version=4c413ee638df813c5a2394255da8740a5ed45bdd
    force=yes

- name: install vopaas
  pip:
    name={{ item }} virtualenv={{ vopaas_env }}
  with_items:
    - "{{ external_dep_src_dir }}/jwkest"
    - "{{ external_dep_src_dir }}/pysaml2"
    - "{{ external_dep_src_dir }}/pyoidc"
    - "{{ external_dep_src_dir }}/satosa"
    - "{{ vopaas_src_dir }}"

- name: install requirements
  pip: name={{ item }} virtualenv={{ vopaas_env }}
  with_items:
    - CherryPy
    - Beaker
    - Werkzeug